# Generated by Django 6.0.3 on 2026-03-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_tripimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
