# Generated by Django 6.0.3 on 2026-03-31 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_tripimage_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripimage',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trips.trip'),
        ),
    ]
