# Generated by Django 6.0.3 on 2026-04-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_alter_tripimage_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
