# Generated by Django 6.0.3 on 2026-04-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Models',
            new_name='Review',
        ),
    ]
