# Generated by Django 6.0.3 on 2026-04-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_rename_models_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
