 # Generated by Django 6.0.3 on 2026-04-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='trip',
            name='description_pl',
            field=models.TextField(default='Temporary descsription', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='title_pl',
            field=models.CharField(default='Temporary title', max_length=100),
            preserve_default=False,
        ),
    ]
