# Generated by Django 6.0.3 on 2026-04-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0017_booking_user_alter_booking_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
