# Generated by Django 6.0.3 on 2026-04-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_tripimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='title_en',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
